image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_NAME: mathewpeterson/php7
  IMAGE_TAG_CLI: ${IMAGE_NAME}:cli
  IMAGE_TAG_FPM: ${IMAGE_NAME}:fpm

before_script:
  - env | sort
  - docker info

stages:
  - build
  - test
  - release

build-cli:
  stage: build
  script:
    - ./ci/build.sh cli

test-cli:
  stage: test
  script:
    - ./ci/test.sh cli

# release-cli:
#  stage: release
#  script:
#    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
#    - docker push $IMAGE_TAG_CLI
